config/routes.rb
Codereviewer::Application.routes.draw do
  

  get "profiles/show"
  get '/:username', to: 'profiles#show'

  devise_for :users

  resources :projects do
    resources :project_comments, :only => [:create]
  end
  
  root :to => 'projects#index'

end

app/models/project.rb
class Project < ActiveRecord::Base
  attr_accessible :content, :description, :title, :user_id, :picture, :language, :avatar, :photo_url
  attr_accessor :avatar_file_name, :avatar_content_type, :avatar_file_size, :avatar_updated_at

  belongs_to :user

  has_many :project_comments

  mount_uploader :picture, PictureUploader

  # This method associates the attribute ":avatar" with a file attachment
  has_attached_file :avatar, styles: {
    thumb: '150x150>',
    square: '200x200#',
    medium: '600x600>'
  }

  # Validate the attached image is image/jpg, image/png, etc
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/


end

app/models/project_comment.rb
class ProjectComment < ActiveRecord::Base
  attr_accessible :body, :project_id, :username

  belongs_to :project

  validates_presence_of :body

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :username, :first_name, :last_name
  # attr_accessible :title, :body

  has_many :projects, dependent: :destroy
  validates_uniqueness_of :username

  def full_name
  	first_name + " " + last_name
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  def show
  	@user = User.where(username: params[:username]).first
  	if @user
  		@projects = @user.projects
  		render action: :show
  	else
  		render file: 'public/404', status: 404, formats: [:html]
  	end
  end
end

app/controllers/project_comments_controller.rb
class ProjectCommentsController < ApplicationController
  # GET /project_comments
  # GET /project_comments.json
  def index
    @project_comments = ProjectComment.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @project_comments }
    end
  end

  # GET /project_comments/1
  # GET /project_comments/1.json
  def show
    @project_comment = ProjectComment.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @project_comment }
    end
  end

  # GET /project_comments/new
  # GET /project_comments/new.json
  def new
    @project_comment = ProjectComment.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @project_comment }
    end
  end

  # GET /project_comments/1/edit
  def edit
    @project_comment = ProjectComment.find(params[:id])
  end

  # POST /project_comments
  # POST /project_comments.json
  def create
    @project = Project.find(params[:project_id])
    @project_comment = @project.project_comments.create!(params[:project_comment])
    redirect_to @project

  end

  # PUT /project_comments/1
  # PUT /project_comments/1.json
  def update
    @project_comment = ProjectComment.find(params[:id])

    respond_to do |format|
      if @project_comment.update_attributes(params[:project_comment])
        format.html { redirect_to @project_comment, notice: 'Project comment was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @project_comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /project_comments/1
  # DELETE /project_comments/1.json
  def destroy
    @project_comment = ProjectComment.find(params[:id])
    @project_comment.destroy

    respond_to do |format|
      format.html { redirect_to project_comments_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  # GET /projects
  # GET /projects.json
  def index
    @projects = Project.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @projects }
    end
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
    @project = Project.find(params[:id])
    @comments = @project.project_comments.all
    @comment = @project.project_comments.build

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @project }
    end
  end

  # GET /projects/new
  # GET /projects/new.json
  def new
    @s3_direct_post = S3_BUCKET.presigned_post(key: "uploads/#{SecureRandom.uuid}/${filename}", success_action_status: 201, acl: :public_read)
    @project = Project.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @project }
    end
  end

  # GET /projects/1/edit
  def edit
    @project = Project.find(params[:id])
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(params[:project])

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render json: @project, status: :created, location: @project }
      else
        format.html { render action: "new" }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /projects/1
  # PUT /projects/1.json
  def update
    @project = Project.find(params[:id])

    respond_to do |format|
      if @project.update_attributes(params[:project])
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project = Project.find(params[:id])
    @project.destroy

    respond_to do |format|
      format.html { redirect_to projects_url }
      format.json { head :no_content }
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/project_comments_helper.rb
module ProjectCommentsHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>The Code Hub</title>
    <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
  <![endif]-->

  <!--link href="prism.css" rel="stylesheet" type="text/css" />
  <script src="prism.js" type="text/javascript"></script-->

<!--Using highlightjs.org-->
  <link rel="stylesheet" href="http://cdnjs.cloudflare.com/ajax/libs/highlight.js/8.1/styles/default.min.css">
  <script src="http://cdnjs.cloudflare.com/ajax/libs/highlight.js/8.1/highlight.min.js"></script>
  <script>hljs.initHighlightingOnLoad();</script>

  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.0.8/angular.min.js"></script>

  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="description" content="Share your code snippets with others. Get feedback. Get ideas. Keep learning!">

</head>
<body>
	<div class="navbar navbar-fixed-top">
	  <div class="navbar-inner">
	    <div class="container">
	      <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
	        <span class="icon-bar"></span>
	        <span class="icon-bar"></span>
	        <span class="icon-bar"></span>
	      </a>
	      <a class="brand" href="/">The Code Hub</a>
	      <div class="nav-collapse">
	        <ul class="nav">
	          <li><%= link_to "Browse All Projects", "/" %></li>

	          <% if user_signed_in? %>
	          <li><%= link_to "New Project", new_project_path %></li>
	          <li><%= link_to "My Projects", "/"+current_user.username %></li>
			  <% end %>

	        </ul>
	      </div>
	      <p class="navbar-text pull-right">
			<% if user_signed_in? %>
			  Logged in as <strong><%= current_user.full_name %></strong>.
			  <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
			  <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
			<% else %>
			  <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
			  <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
			<% end %>
	    </div>
	  </div>
	</div>

	<div class="container">
		<div class="row">
			<% if notice %>
			  <p class="alert alert-success"><%= notice %></p>
			<% end %>
			<% if alert %>
			  <p class="alert alert-danger"><%= alert %></p>
			<% end %>
		    <div class="span12"><%= yield %></div>
		    
		  </div>
	</div>

</body>
</html>

app/views/profiles/show.html.erb
<%- model_class = Project -%>
<h1>
	<%= @user.full_name %>
</h1>

<% if @projects and !@projects.empty? %>

	<% @projects.each do |project| %>
	  <div class="well">
	    <%= image_tag(project.photo_url, :style => "float:left; padding:0px 20px 0px 0px; width: 120px; height: 120px;") if project.photo_url.present? %>
	    <h4><%= link_to project.title, project_path(project) %></h4>
	    <p>Language: <%= project.language %></p>
	    <p><%= project.description %></p>

	    <% if user_signed_in? and current_user.id == project.user.id %>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_project_path(project), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      project_path(project),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>

	    <% end %>
	  </div>
	<% end %>


<% else %>
	
	<br><br><br><br><br>
	<p> Kinda boring... No projects yet </p>


<% end %>

app/views/project_comments/_form.html.erb
<%= simple_form_for(@project_comment) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :body %>
    <%= f.hidden_field :project_id%>
    <%= f.hidden_field :username, :value => current_user.username %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/project_comments/_project_comments.html.erb
<%= div_for comment do %>
  <p>
     <strong>
        Posted <%= time_ago_in_words(comment.created_at) %> ago
     </strong>
     <br/>
     <%= comment.body %>
  </p>
<% end %>

app/views/project_comments/edit.html.erb
<h1>Editing project_comment</h1>

<%= render 'form' %>

<%= link_to 'Show', @project_comment %> |
<%= link_to 'Back', project_comments_path %>

app/views/project_comments/index.html.erb
<h1>Listing project_comments</h1>

<table>
  <tr>
    <th>Username</th>
    <th>Body</th>
    <th>Project</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @project_comments.each do |project_comment| %>
  <tr>
    <td><%= project_comment.username %></td>
    <td><%= project_comment.body %></td>
    <td><%= project_comment.project_id %></td>
    <td><%= link_to 'Show', project_comment %></td>
    <td><%= link_to 'Edit', edit_project_comment_path(project_comment) %></td>
    <td><%= link_to 'Destroy', project_comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Project comment', new_project_comment_path %>

app/views/project_comments/new.html.erb
<h1>New project_comment</h1>

<%= render 'form' %>

<%= link_to 'Back', project_comments_path %>

app/views/project_comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Username:</b>
  <%= @project_comment.username %>
</p>

<p>
  <b>Body:</b>
  <%= @project_comment.body %>
</p>

<p>
  <b>Project:</b>
  <%= @project_comment.project_id %>
</p>


<%= link_to 'Edit', edit_project_comment_path(@project_comment) %> |
<%= link_to 'Back', project_comments_path %>

app/views/projects/_form.html.erb
<div class="span9">

  <%= simple_form_for @project, :html => {:multipart => true, class: "directUpload"} do |f| %>
    <%= f.error_notification %>

    <%= f.input :title, :autofocus => true, required: true, :input_html => {:style=> 'width: 600px'} %>

    <%= f.input :language, required: true, :collection => ['Java', 'Python', 'C/C++/C#', 'Objective-C', 'Javascript', 'Processing', 'HTML', 'CSS', 'Alice', 'Scratch', 'Ruby (on Rails)', 'Swift', 'Other'], :input_html => {:style=> 'width: 610px'}  %>

    <%= f.input :description, required: true, :input_html => {:style=> 'width: 600px; height: 50px;'} %>

    <%= f.input :photo_url, :autofocus => true, required: true, placeholder: 'Post photo online at postimage.org and then copy link here', :input_html => {:style=> 'width: 600px'} %>

    <%= f.input :content, required: true, label: 'Code', :input_html => {:style=> 'width: 600px'} %>

    <%= f.hidden_field :user_id, :value => current_user.id %>
    
    <div class="form-actions">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                  projects_path, :class => 'btn' %>
    </div>

    <br/>
  <% end %>

</div>

app/views/projects/edit.html.erb
<%- model_class = Project -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/projects/index.html.erb
<%- model_class = Project -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>

<% @projects.each do |project| %>
  <div class="well">
    <%= image_tag(project.photo_url, :style => "float:left; padding:0px 20px 0px 0px; width: 120px; height: 120px;") if project.photo_url.present? %>
    <h4><%= link_to project.title, project_path(project) %></h4>
    <p>By: <%= link_to project.user.full_name, "/" + project.user.username %></p>
    <p>Language: <%= project.language %></p>
    <p><%= project.description %></p>
  </div>
<% end %>

app/views/projects/new.html.erb
<%- model_class = Project -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>


<%= render :partial => 'form' %>

app/views/projects/show.html.erb
<%- model_class = Project -%>
<div class="page-header row">

  <div class="span7">
  <h1><%= @project.title %></h1>
  <p> <%= @project.description %> </p>
  <p> Language: <%= @project.language %> </p>
  <p> By: <%= link_to @project.user.full_name, "/" + @project.user.username %> </p>
  </div>

  <div class="span3">
  <!-- project pic -->
  <%= image_tag(@project.photo_url) if @project.photo_url.present? %>
  

  </div>
</div>

<div class="row">

  <div class="cr-code selectable">
  <!-- project code -->
    <pre><code>
    <%= @project.content %>
    </code></pre>
  </div>


</div>
<!-- project actions: Edit | Delete -->
<% if user_signed_in? and @project.user_id == current_user.id %>
  <div class="form-actions">
    <%= link_to t('.edit', :default => t("helpers.links.edit")),
                edit_project_path(@project), :class => 'btn' %>
    <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                project_path(@project),
                :method => 'delete',
                :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                :class => 'btn btn-danger' %>
  </div>
<% end %>

<hr>

<h3>Comments</h3>
<!-- project comments -->
  <% @comments.each do |comment| %>
  <div>
    <strong><%= link_to comment.username, "/"+comment.username %></strong>  &nbsp;&nbsp;&nbsp;
    Posted <%= time_ago_in_words(comment.created_at) %> ago
    <br />
    <p><%= comment.body %></p>
  </div>
  <% end %>
  <% if @comments.empty? %>
    No comments yet. Be the first!
  <% end %>

<% if user_signed_in? %>
  <br />
  <%= simple_form_for [@project, ProjectComment.new] do |f| %>
        <p>
            <%= f.input :body, label: 'New Comment', :input_html => {:style=> 'width: 600px; height: 50px;'} %>
            <%= f.hidden_field :username, :value => current_user.username %>
        </p>
        <div class="form-actions">
      <%= f.submit nil, :class => 'btn', label: 'Add Comment' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                  projects_path, :class => 'btn' %>
    </div>
  <% end %>
<% else %>
  <br />
  <%= link_to "Login", new_user_session_path %> to add a comment.
  <br /><br /><br />
<% end %>